//contstants to get exhibition lists
export const EXHIBITION_LIST_REQUEST = "EXHIBITION_LIST_REQUEST";
export const EXHIBITION_LIST_SUCCESS = "EXHIBITION_LIST_SUCCESS";
export const EXHIBITION_LIST_ERROR = "EXHIBITION_LIST_ERROR";

//constants to get products list
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR";

//constants to register a user(exhibitor/fabricator) 
export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_ERROR = "USER_REGISTRATION_ERROR";

//constants to create a exhibition
export const CREATE_EXHIBITION_REQUEST = "CREATE_EXHIBITION_REQUEST";
export const CREATE_EXHIBITION_SUCCESS = "CREATE_EXHIBITION_SUCCESS";
export const CREATE_EXHIBITION_ERROR = "CREATE_EXHIBITION_ERROR";

//constants to get profile(exhibitor/fabricator)
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";

//constants to update profile(exhibitor/fabricator)
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

//constants to get profile(exhibitor/fabricator) after update
export const USER_PROFILE_AFTER_UPDATE_REQUEST ="USER_PROFILE_AFTER_UPDATE_REQUEST";
export const USER_PROFILE_AFTER_UPDATE_SUCCESS ="USER_PROFILE_AFTER_UPDATE_SUCCESS";

//constants to clear update reducer
export const CLEAR_UPDATE_REQUEST ="CLEAR_UPDATE_REQUEST";
export const CLEAR_UPDATE_SUCCESS ="CLEAR_UPDATE_SUCCESS";

//constants to clear update reducer
export const CLEAR_USERPROFILE_REQUEST ="CLEAR_USERPROFILE_REQUEST";
export const CLEAR_USERPROFILE_SUCCESS ="CLEAR_USERPROFILE_SUCCESS";

//constants to upload portfolio(fabricator)
export const UPLOAD_PORTFOLIO_REQUEST = "UPLOAD_PORTFOLIO_REQUEST";
export const UPLOAD_PORTFOLIO_SUCCESS = "UPLOAD_PORTFOLIO_SUCCESS";
export const UPLOAD_PORTFOLIO_ERROR = "UPLOAD_PORTFOLIO_ERROR";

//constants to delete portfolio(fabricator)
export const DELETE_PORTFOLIO_REQUEST = "DELETE_PORTFOLIO_REQUEST";
export const DELETE_PORTFOLIO_SUCCESS = "DELETE_PORTFOLIO_SUCCESS";
export const DELETE_PORTFOLIO_ERROR = "DELETE_PORTFOLIO_ERROR";

//constants to get fabricator's list
export const FABRICATOR_LIST_REQUEST = "FABRICATOR_LIST_REQUEST";
export const FABRICATOR_LIST_SUCCESS = "FABRICATOR_LIST_SUCCESS";
export const FABRICATOR_LIST_ERROR = "FABRICATOR_LIST_ERROR";

//constants to clear fabricator's list
export const CLEAR_FABRICATOR_LIST_REQUEST = "CLEAR_FABRICATOR_LIST_REQUEST";
export const CLEAR_FABRICATOR_LIST_SUCCESS = "CLEAR_FABRICATOR_LIST_SUCCESS";

//constants to add fabricator to quote by exhibitor
export const ADD_FABRICATOR_REQUEST = "ADD_FABRICATOR_REQUEST";
export const ADD_FABRICATOR_SUCCESS = "ADD_FABRICATOR_SUCCESS";
export const ADD_FABRICATOR_ERROR = "ADD_FABRICATOR_ERROR";




