//contstants to get exhibition lists

export const EXHIBITION_LIST_REQUEST = "EXHIBITION_LIST_REQUEST";
export const EXHIBITION_LIST_SUCCESS = "EXHIBITION_LIST_SUCCESS";
export const EXHIBITION_LIST_ERROR = "EXHIBITION_LIST_ERROR";